from __future__ import annotations

from io import BytesIO
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

MAX_REPORT_BYTES = 16 * 1024 * 1024


class ReportRenderingError(RuntimeError):
    """Raised when a human-readable report cannot be rendered safely."""


def render_examination_report(report: dict[str, Any]) -> bytes:
    """Render a bounded, static PDF from an already-normalized report payload."""
    stream = BytesIO()
    styles = _styles()
    try:
        document = SimpleDocTemplate(
            stream,
            pagesize=A4,
            rightMargin=18 * mm,
            leftMargin=18 * mm,
            topMargin=21 * mm,
            bottomMargin=20 * mm,
            title=str(report["report_title"]),
            author="ForenX",
            subject="CCTV forensic examination report",
        )
        story: list[Any] = [
            Paragraph("FORENX / EXAMINATION REPORT", styles["eyebrow"]),
            Paragraph(_safe(report["report_title"]), styles["title"]),
            Paragraph(
                "Digitally signed evidence-package report. Conclusions remain subject to "
                "applicable law, procedure, and expert testimony.",
                styles["subtitle"],
            ),
            Spacer(1, 5 * mm),
        ]
        _add_section(
            story,
            "Report identity",
            (
                ("Report ID", report["report_id"]),
                ("Generated at (UTC)", report["created_at"]),
                ("Generated by", report["created_by_display"]),
                ("Operator role", report["created_by_role"]),
                ("ForenX version", report["tool"]["version"]),
            ),
            styles,
        )
        case = report["case"]
        _add_section(
            story,
            "Case",
            (
                ("Case reference", case["case_reference"]),
                ("Agency", case["agency"]),
                ("Police station", case.get("police_station")),
                ("Investigating officer", case["investigating_officer"]),
                ("Classification", case["classification"]),
                ("Workflow status", case["status"]),
            ),
            styles,
        )
        exhibit = report["exhibit"]
        _add_section(
            story,
            "Exhibit and authority",
            (
                ("Exhibit number", exhibit["exhibit_number"]),
                ("Device type", exhibit["device_type"]),
                (
                    "Manufacturer / model",
                    _joined(exhibit.get("manufacturer"), exhibit.get("model")),
                ),
                ("Serial number", exhibit.get("serial_number")),
                (
                    "Seal number / condition",
                    _joined(exhibit.get("seal_number"), exhibit["seal_condition"]),
                ),
                ("Collected by", exhibit["collector"]),
                ("Collection location", exhibit["collection_location"]),
                ("Collected at", exhibit["collected_at"]),
                ("Authority reference", exhibit["authorization_reference"]),
                ("Recorder clock offset", _clock_offset(exhibit.get("clock_offset_seconds"))),
            ),
            styles,
        )
        source = report["source_evidence"]
        _add_section(
            story,
            "Source evidence integrity",
            (
                ("Original filename", source["original_filename"]),
                ("Media kind", source["media_kind"]),
                ("Byte size", f'{source["byte_size"]:,}'),
                ("SHA-256", source["sha256"]),
                ("Integrity re-check", "PASSED" if source["integrity_verified"] else "FAILED"),
                ("Source treatment", "Protected read-only vault copy; no source bytes modified"),
            ),
            styles,
        )
        recovery_provenance = source.get("recovery_provenance")
        if recovery_provenance:
            derivation = recovery_provenance["derivation"]
            extents = derivation.get("source_extents", [])
            _add_section(
                story,
                "Recovered-stream provenance",
                (
                    (
                        "Parent disk image",
                        recovery_provenance["parent_original_filename"],
                    ),
                    ("Parent SHA-256", recovery_provenance["parent_sha256"]),
                    (
                        "Parent integrity re-check",
                        "PASSED"
                        if recovery_provenance["parent_integrity_verified"]
                        else "FAILED",
                    ),
                    ("Recovery scan", derivation.get("scan_id")),
                    ("Recording descriptor", derivation.get("recording_id")),
                    (
                        "Physical source extents",
                        "; ".join(
                            f'offset {item["offset"]}, length {item["length"]}'
                            for item in extents
                        ),
                    ),
                    ("Recovery artifact SHA-256", derivation.get("artifact_sha256")),
                    (
                        "Transformation",
                        "Exact source-extent copy; the parent disk image remains controlling",
                    ),
                ),
                styles,
            )
        inspection = report["media_inspection"]
        primary_video = next(
            (
                stream_info
                for stream_info in inspection["streams"]
                if stream_info["type"] == "video"
            ),
            None,
        )
        _add_section(
            story,
            "Technical media inspection",
            (
                ("Container", inspection["format_long_name"]),
                ("Duration", _duration(inspection.get("duration_seconds"))),
                ("Video codec", primary_video.get("codec_long_name") if primary_video else None),
                ("Resolution", _resolution(primary_video)),
                ("Average frame rate", _frame_rate(primary_video)),
                ("Inspection engine", f'{inspection["library"]} {inspection["library_version"]}'),
                ("Inspected at", report["inspection_recorded_at"]),
            ),
            styles,
        )
        _add_narrative(story, "Purpose and scope", report["purpose"], styles)
        _add_narrative(story, "Examiner conclusion", report["examiner_conclusion"], styles)
        _add_bookmarks(story, report["bookmarks"], styles)
        _add_biometric_analysis(
            story,
            report.get("biometric_authorizations", []),
            report.get("face_detection_runs", []),
            report.get("face_tracking_runs", []),
            styles,
        )
        _add_limitations(story, report["limitations"], styles)
        _add_section(
            story,
            "Verification",
            (
                ("Case activity chain", "VERIFIED"),
                ("Activity events captured", report["activity_verification"]["checked_events"]),
                ("Signing algorithm", "Ed25519"),
                ("Signing-key fingerprint", report["signing_key_fingerprint"]),
                (
                    "Independent verification",
                    "Run forenx-verify against the extracted package directory",
                ),
                (
                    "Section 63(4) support",
                    "Unsigned worksheet and source hash report included; authorized "
                    "signatories must complete and legally review the certificate",
                ),
            ),
            styles,
        )
        document.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    except (KeyError, TypeError, ValueError) as exc:
        raise ReportRenderingError("Report data is incomplete or invalid") from exc
    payload = stream.getvalue()
    if not payload.startswith(b"%PDF-") or len(payload) > MAX_REPORT_BYTES:
        raise ReportRenderingError("Rendered report is invalid or exceeds its size limit")
    return payload


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "eyebrow": ParagraphStyle(
            "ForenXEyebrow",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#0F766E"),
            spaceAfter=4,
        ),
        "title": ParagraphStyle(
            "ForenXTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=27,
            textColor=colors.HexColor("#102A2B"),
            spaceAfter=5,
        ),
        "subtitle": ParagraphStyle(
            "ForenXSubtitle",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#526566"),
        ),
        "heading": ParagraphStyle(
            "ForenXHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#102A2B"),
            spaceBefore=5,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "ForenXBody",
            parent=base["BodyText"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#263E40"),
        ),
        "label": ParagraphStyle(
            "ForenXLabel",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#526566"),
        ),
        "value": ParagraphStyle(
            "ForenXValue",
            parent=base["Normal"],
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#102A2B"),
            wordWrap="CJK",
        ),
        "time": ParagraphStyle(
            "ForenXTime",
            parent=base["Normal"],
            fontName="Courier-Bold",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#0F766E"),
            alignment=TA_RIGHT,
        ),
    }


def _add_section(
    story: list[Any],
    title: str,
    rows: tuple[tuple[str, object], ...],
    styles: dict[str, ParagraphStyle],
) -> None:
    table_rows = [
        [Paragraph(_safe(label), styles["label"]), Paragraph(_safe(value), styles["value"])]
        for label, value in rows
    ]
    table = Table(table_rows, colWidths=(47 * mm, 111 * mm), hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F6F5")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D4E1DF")),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(KeepTogether([Paragraph(_safe(title), styles["heading"]), table]))


def _add_narrative(
    story: list[Any],
    title: str,
    value: object,
    styles: dict[str, ParagraphStyle],
) -> None:
    story.extend(
        (
            Paragraph(_safe(title), styles["heading"]),
            Paragraph(_safe(value), styles["body"]),
        )
    )


def _add_bookmarks(
    story: list[Any],
    bookmarks: list[dict[str, Any]],
    styles: dict[str, ParagraphStyle],
) -> None:
    story.append(Paragraph("Timeline observations", styles["heading"]))
    if not bookmarks:
        story.append(Paragraph("No examiner bookmarks were recorded.", styles["body"]))
        return
    for bookmark in bookmarks:
        note = bookmark.get("note") or "No additional note."
        row = Table(
            [[
                Paragraph(_timecode(bookmark["timestamp_ms"]), styles["time"]),
                Paragraph(
                    f'<b>{_safe(bookmark["title"])}</b><br/>{_safe(note)}',
                    styles["body"],
                ),
            ]],
            colWidths=(30 * mm, 128 * mm),
        )
        row.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D4E1DF")),
                    ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#E7F4F1")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 7),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.extend((KeepTogether(row), Spacer(1, 2 * mm)))


def _add_limitations(
    story: list[Any],
    limitations: list[str],
    styles: dict[str, ParagraphStyle],
) -> None:
    story.append(Paragraph("Limitations and qualification", styles["heading"]))
    for limitation in limitations:
        story.append(Paragraph(f"- {_safe(limitation)}", styles["body"]))


def _add_biometric_analysis(
    story: list[Any],
    authorizations: object,
    runs: object,
    tracking_runs: object,
    styles: dict[str, ParagraphStyle],
) -> None:
    if (
        not isinstance(authorizations, list)
        or not isinstance(runs, list)
        or not isinstance(tracking_runs, list)
    ):
        raise TypeError("Biometric report records must be lists")
    story.append(Paragraph("Controlled face-detection observations", styles["heading"]))
    story.append(
        Paragraph(
            "Face-location observations do not establish identity. The decoded-frame "
            "previews are signed package artifacts; exact detections remain in the JSON report.",
            styles["body"],
        )
    )
    if not authorizations and not runs and not tracking_runs:
        story.append(Paragraph("No controlled face analysis was recorded.", styles["body"]))
        return
    for authorization in authorizations:
        if not isinstance(authorization, dict):
            raise TypeError("Biometric authorization must be an object")
        _add_section(
            story,
            "Biometric analysis authorization",
            (
                ("Authorization ID", authorization["authorization_id"]),
                ("Mode", authorization["mode"]),
                ("Purpose", authorization["purpose"]),
                ("Legal-authority reference", authorization["legal_authority_reference"]),
                ("Reference provenance", authorization["reference_provenance"]),
                ("Retention deadline", authorization["retention_until"]),
                ("Threshold policy", authorization["threshold_policy"]),
                ("Authorized by", authorization["authorized_by"]),
            ),
            styles,
        )
    for run in runs:
        if not isinstance(run, dict):
            raise TypeError("Face-detection run must be an object")
        _add_section(
            story,
            f'Face-detection run {_safe(run["run_id"])}',
            (
                ("Requested source time", _timecode(run["requested_timestamp_ms"])),
                ("Observed source time", _timecode(run["observed_timestamp_ms"])),
                ("Faces located", len(run["faces"])),
                ("Detector", f'{run["model_name"]} {run["model_version"]}'),
                ("Model SHA-256", run["model_sha256"]),
                ("Decoded-frame SHA-256", run["source_frame_sha256"]),
                ("Preview artifact", run["preview_artifact"]),
                ("Preview SHA-256", run["preview_sha256"]),
                (
                    "Thresholds",
                    f'score >= {float(run["score_threshold"]):.3f}; '
                    f'NMS {float(run["nms_threshold"]):.3f}',
                ),
                ("Authorization ID", run["authorization_id"]),
            ),
            styles,
        )
    for tracking in tracking_runs:
        if not isinstance(tracking, dict):
            raise TypeError("Face-tracking run must be an object")
        tracks = tracking["tracks"]
        if not isinstance(tracks, list):
            raise TypeError("Face tracks must be a list")
        observation_count = sum(
            len(track.get("observations", []))
            for track in tracks
            if isinstance(track, dict)
        )
        _add_section(
            story,
            f'Geometric face-tracking run {_safe(tracking["tracking_run_id"])}',
            (
                ("Selected range start", _timecode(tracking["start_timestamp_ms"])),
                ("Selected range end", _timecode(tracking["end_timestamp_ms"])),
                ("Distinct decoded frames", tracking["distinct_frame_count"]),
                ("Geometric tracks", len(tracks)),
                ("Track observations", observation_count),
                (
                    "Association rule",
                    f'{tracking["algorithm"]} {tracking["algorithm_version"]}; '
                    f'IoU >= {float(tracking["iou_threshold"]):.3f}; '
                    f'max gap {int(tracking["max_gap_ms"])} ms',
                ),
                ("Authorization ID", tracking["authorization_id"]),
                (
                    "Qualification",
                    "Geometric continuity hypothesis only; not identity recognition",
                ),
            ),
            styles,
        )


def _page_footer(canvas: Any, document: Any) -> None:
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#D4E1DF"))
    canvas.line(18 * mm, 14 * mm, A4[0] - 18 * mm, 14 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#526566"))
    canvas.drawString(18 * mm, 9.5 * mm, "ForenX - generated forensic examination report")
    canvas.drawRightString(A4[0] - 18 * mm, 9.5 * mm, f"Page {document.page}")
    canvas.restoreState()


def _safe(value: object) -> str:
    if value is None or str(value).strip() == "":
        return "Not recorded"
    return escape(str(value).strip())


def _joined(first: object, second: object) -> str:
    values = [
        str(value).strip()
        for value in (first, second)
        if value is not None and str(value).strip()
    ]
    return " / ".join(values) if values else "Not recorded"


def _clock_offset(value: object) -> str:
    if value is None:
        return "Not recorded"
    if not isinstance(value, (int, float, str)):
        return "Not recorded"
    seconds = int(value)
    sign = "+" if seconds >= 0 else "-"
    return f"{sign}{abs(seconds)} seconds"


def _duration(value: object) -> str:
    if value is None:
        return "Not reported by container"
    if not isinstance(value, (int, float, str)):
        return "Not reported by container"
    return f"{float(value):.3f} seconds"


def _resolution(stream: dict[str, Any] | None) -> str:
    if stream is None or stream.get("width") is None or stream.get("height") is None:
        return "Not reported"
    return f'{stream["width"]} x {stream["height"]}'


def _frame_rate(stream: dict[str, Any] | None) -> str:
    if stream is None or stream.get("average_frame_rate") is None:
        return "Not reported"
    return f'{float(stream["average_frame_rate"]):.3f} fps'


def _timecode(timestamp_ms: object) -> str:
    if not isinstance(timestamp_ms, (int, float, str)):
        return "00:00:00.000"
    total = max(0, int(timestamp_ms))
    milliseconds = total % 1000
    total_seconds = total // 1000
    seconds = total_seconds % 60
    minutes = (total_seconds // 60) % 60
    hours = total_seconds // 3600
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{milliseconds:03d}"
